<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Blackjack</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <style>
            body {
                text-align: center;
            }
        </style>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <h1>Blackjack</h1>
                <h3>Team vs Team</h2>
                <div class="container">
                    <div class="col s6">
                        <p>42 players</p>
                        <form action="/teams" method="get">
                            <button class="btn waves-effect waves-light red" type="submit">Team red
                                <i class="material-icons right">group</i>
                            </button>
                        </form>
                    </div>
                </div>
                <div class="container">
                    <div class="col s6">
                        <p>21 players</p>
                        <form action="/teams/blue" method="get">
                            <button class="btn waves-effect waves-light blue" type="submit">Team blue
                                <i class="material-icons right">group</i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
