<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Blackjack</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.5.1"></script>
        <link rel="stylesheet" href="/css/style.css">
        <script src="js/index.js"></script>
    </head>
    <body>
        <nav>
            <div class="nav-wrapper">
                <div class="col s12 grey darken-3">
                    <a href="#!" class="breadcrumb">Blackjack</a>
                </div>
            </div>
        </nav>
        <div id="app" class="container">
            <div class="row">
                <h3>Team vs Team</h2>
                <div class="container">
                    <div class="col s5">
                        <p>{{redPlayers}} players</p>
                        <form action="/teams/red" method="get">
                            <button class="btn waves-effect waves-light red" type="submit">Team red
                                <i class="material-icons right">group</i>
                            </button>
                        </form>
                    </div>
                </div>
                <div class="container">
                    <div class="col s2">
                        <div id="rulesButton" class="col s2">
                            <a class="btn waves-effect waves-light grey darken-3" type="submit" 
                            href="https://www.bicyclecards.com/how-to-play/blackjack/" target="_blank" name="rules">Rules</a>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="col s5">
                        <p>{{bluePlayers}} players</p>
                        <form action="/teams/blue" method="get">
                            <button class="btn waves-effect waves-light blue" type="submit">Team blue
                                <i class="material-icons right">group</i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
