<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Blackjack</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <style>
            body {
                text-align: center;
            }
        </style>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.5.1"></script>
        <link rel="stylesheet" href="/css/cards.css">
    </head>
    <body>
        <nav>
            <div class="nav-wrapper">
                <div class="col s12 <?= $team ?>">
                    <a href="/" class="breadcrumb">Blackjack</a>
                    <a href="#!" class="breadcrumb">Team <?= $team ?></a>
                </div>
            </div>
        </nav>
        <div id="app" class="container">
            <div class="row">
                <div id="app">
                    <h2>Welcome to team <?= $team ?></h2>
                    <div class="container">
                        <div id="redButtons" class="col s6">
                            <button class="btn waves-effect waves-light red" type="submit" name="hit">Hit</button>
                            <button class="btn waves-effect waves-light red" type="submit" name="stand">Stand</button>
                        </div>
                        <ul id="redCards" style="list-style-type:none">
                            <li style="left:0px;z-index:0;position:absolute"></li>
                            <li style="left:100px;z-index:1;position:absolute"></li>
                            <li style="left:200px;z-index:2;position:absolute"></li>
                            <li style="left:300px;z-index:3;position:absolute"></li>
                            <li style="left:400px;z-index:4;position:absolute"></li>
                            <li style="left:500px;z-index:5;position:absolute"></li>
                            <li style="left:600px;z-index:6;position:absolute"></li>
                            <li style="left:700px;z-index:7;position:absolute"></li>
                            <li style="left:800px;z-index:8;position:absolute"></li>
                            <li style="left:900px;z-index:9;position:absolute"></li>
                            <li style="left:1000px;z-index:10;position:absolute"></li>
                            <li style="left:1100px;z-index:11;position:absolute"></li>
                            <li style="left:1200px;z-index:12;position:absolute"></li>
                        </ul>
                    </div>
                    <div class="container">
                        <div id="blueButtons" class="col s6">
                            <button class="btn waves-effect waves-light blue" type="submit" name="hit">Hit</button>
                            <button class="btn waves-effect waves-light blue" type="submit" name="stand">Stand</button>
                        </div>
                        <ul id="blueCards" style="list-style-type:none">
                            <li style="left:0px;z-index:0;position:absolute"></li>
                            <li style="left:100px;z-index:1;position:absolute"></li>
                            <li style="left:200px;z-index:2;position:absolute"></li>
                            <li style="left:300px;z-index:3;position:absolute"></li>
                            <li style="left:400px;z-index:4;position:absolute"></li>
                            <li style="left:500px;z-index:5;position:absolute"></li>
                            <li style="left:600px;z-index:6;position:absolute"></li>
                            <li style="left:700px;z-index:7;position:absolute"></li>
                            <li style="left:800px;z-index:8;position:absolute"></li>
                            <li style="left:900px;z-index:9;position:absolute"></li>
                            <li style="left:1000px;z-index:10;position:absolute"></li>
                            <li style="left:1100px;z-index:11;position:absolute"></li>
                            <li style="left:1200px;z-index:12;position:absolute"></li>
                        </ul>
                    </div>
                        <div id="redResults" class="col s6">
                            <p>50% voted Hit (4)</p>
                            <p>50% voted Stand (4)</p>
                        </div>
                        <div id="blueResults" class="col s6">
                        <p>50% voted Hit (4)</p>
                        <p>50% voted Stand (4)</p>
                        </div>
                        <div id="quitButton" class="col s12">
                            <button class="btn waves-effect waves-light grey darken-3" type="submit" onclick="window.location.href='/'" name="quit">Quit</button>
                        </div>
                </div>
            </div>
        </div>
        <script src="/js/app.js"></script>
    </body>
</html>
