<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Blackjack</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <style>
            body {
                text-align: center;
            }
        </style>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    </head>
    <body>
    <div>
        <div id="app">
            <h1>Team: <blank style="color: <?= $team ?>"><?= $team ?></blank></h1>
        </div>
        <div id="buttonsTeam1" class="col s6 offset-s6">
            <button class="btn waves-effect waves-light" type="submit" name="hit">Hit</button>
            <button class="btn waves-effect waves-light" type="submit" name="stand">Stand</button>
        </div>
        <div id="buttonsTeam2" class="col s6 offset-s6">
            <button class="btn waves-effect waves-light" type="submit" name="hit">Hit</button>
            <button class="btn waves-effect waves-light" type="submit" name="stand">Stand</button>
        </div>
    </div>
    </body>
    <script src="js/app.js"></script>
</html>
